language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.0.7
  - DJANGO_VERSION=1.11.14
branches:
  only:
    - master
# Start services.
services:
  - redis-server
  - postgresql
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements/local.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE bootcamp;" -U postgres
  - cp .env.example .env
  - python manage.py migrate
  - python manage.py collectstatic --noinput
# command to run tests
script:
  - pytest
after_success:
  - coveralls
